package apptree

var Config1 = `{
    "success": true,
    "message": null,
    "showMessageAsAlert": false,
    "async": false,
    "name": "Jaggaer Purchase Orders",
    "attributes": [
        {
            "name": "Type",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 0
        },
        {
            "name": "Requisition Reference ID",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 2
        },
        {
            "name": "Requestor Username",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 21
        },
        {
            "name": "Requestor First Name",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 3
        },
        {
            "name": "Requestor Last Name",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 4
        },
        {
            "name": "Requestor Email",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 5
        },
        {
            "name": "Requestor Phone",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 6
        },
        {
            "name": "Create Date",
            "attributeType": "DateTime",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 1
        },
        {
            "name": "Bill To Address Lines",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 7
        },
        {
            "name": "Bill To Address City",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 8
        },
        {
            "name": "Bill To Address State",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 9
        },
        {
            "name": "Bill To Address Postal Code",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 10
        },
        {
            "name": "Bill To Address ISO Country Code",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 11
        },
        {
            "name": "Bill To Address Country",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 12
        },
        {
            "name": "Ship To Address Template Name",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 27
        },
        {
            "name": "Ship To Address Lines",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 13
        },
        {
            "name": "Ship To Address City",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 14
        },
        {
            "name": "Ship To Address State",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 15
        },
        {
            "name": "Ship To Address Postal Code",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 16
        },
        {
            "name": "Ship To Address ISO Country Code",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 17
        },
        {
            "name": "Ship To Address Country",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 18
        },
        {
            "name": "Revision Number",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 20
        },
        {
            "name": "Supplier ID",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 22
        },
        {
            "name": "Supplier Name",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 23
        },
        {
            "name": "Supplier Number",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 24
        },
        {
            "name": "Supplier Third Party Reference Number",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 25
        },
        {
            "name": "Supplier Fulfillment Address ID",
            "attributeType": "Text",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 26
        },
        {
            "name": "Purchase Order lines",
            "relatedService": {
                "success": true,
                "message": null,
                "showMessageAsAlert": false,
                "async": false,
                "name": "Purchase Requisition Lines",
                "attributes": [
                    {
                        "name": "Id",
                        "attributeType": "Integer",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 0
                    },
                    {
                        "name": "Workflow Status",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 1
                    },
                    {
                        "name": "Line Number",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 2
                    },
                    {
                        "name": "Requested Delivery Date",
                        "attributeType": "DateTime",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 3
                    },
                    {
                        "name": "Description",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 4
                    },
                    {
                        "name": "Product Unit of Measure",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 5
                    },
                    {
                        "name": "Product Size",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 6
                    },
                    {
                        "name": "Lead Time Days",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 7
                    },
                    {
                        "name": "Barcode",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 8
                    },
                    {
                        "name": "Quantity",
                        "attributeType": "Integer",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 9
                    },
                    {
                        "name": "Requisition Line Reference",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 10
                    },
                    {
                        "name": "Taxable",
                        "attributeType": "Boolean",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 11
                    },
                    {
                        "name": "UNSPSC",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 18
                    },
                    {
                        "name": "Unit Price",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 12
                    },
                    {
                        "name": "Shipping Charges",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 13
                    },
                    {
                        "name": "Handling Charges",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 14
                    },
                    {
                        "name": "Tax 1",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 15
                    },
                    {
                        "name": "Tax 2",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 16
                    },
                    {
                        "name": "Custom Field Value Set",
                        "relatedService": {
                            "success": true,
                            "message": null,
                            "showMessageAsAlert": false,
                            "async": false,
                            "name": "Purchasing Custom Fields",
                            "attributes": [
                                {
                                    "name": "Name",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 0
                                },
                                {
                                    "name": "Label",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 1
                                },
                                {
                                    "name": "Distribution Type",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 2
                                },
                                {
                                    "name": "Distribution Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 3
                                },
                                {
                                    "name": "Distribution Split Index",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 4
                                },
                                {
                                    "name": "Distribution Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 5
                                },
                                {
                                    "name": "Shipping Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 6
                                },
                                {
                                    "name": "Handling Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 7
                                },
                                {
                                    "name": "Tax 1 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 8
                                },
                                {
                                    "name": "Tax 2 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 9
                                },
                                {
                                    "name": "Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 10
                                },
                                {
                                    "name": "Description",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 11
                                }
                            ],
                            "serviceFilterParameters": null,
                            "contextInfo": {},
                            "attributeConfigurationForIndexMap": {
                                "0": {
                                    "name": "Name",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 0
                                },
                                "1": {
                                    "name": "Label",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 1
                                },
                                "2": {
                                    "name": "Distribution Type",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 2
                                },
                                "3": {
                                    "name": "Distribution Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 3
                                },
                                "4": {
                                    "name": "Distribution Split Index",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 4
                                },
                                "5": {
                                    "name": "Distribution Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 5
                                },
                                "6": {
                                    "name": "Shipping Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 6
                                },
                                "7": {
                                    "name": "Handling Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 7
                                },
                                "8": {
                                    "name": "Tax 1 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 8
                                },
                                "9": {
                                    "name": "Tax 2 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 9
                                },
                                "10": {
                                    "name": "Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 10
                                },
                                "11": {
                                    "name": "Description",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 11
                                }
                            },
                            "dependentLists": null,
                            "platformVersion": "5.5"
                        },
                        "attributeType": "Relationship",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 17
                    }
                ],
                "serviceFilterParameters": null,
                "contextInfo": {},
                "attributeConfigurationForIndexMap": {
                    "0": {
                        "name": "Id",
                        "attributeType": "Integer",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 0
                    },
                    "1": {
                        "name": "Workflow Status",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 1
                    },
                    "2": {
                        "name": "Line Number",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 2
                    },
                    "3": {
                        "name": "Requested Delivery Date",
                        "attributeType": "DateTime",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 3
                    },
                    "4": {
                        "name": "Description",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 4
                    },
                    "5": {
                        "name": "Product Unit of Measure",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 5
                    },
                    "6": {
                        "name": "Product Size",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 6
                    },
                    "7": {
                        "name": "Lead Time Days",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 7
                    },
                    "8": {
                        "name": "Barcode",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 8
                    },
                    "9": {
                        "name": "Quantity",
                        "attributeType": "Integer",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 9
                    },
                    "10": {
                        "name": "Requisition Line Reference",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 10
                    },
                    "11": {
                        "name": "Taxable",
                        "attributeType": "Boolean",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 11
                    },
                    "12": {
                        "name": "Unit Price",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 12
                    },
                    "13": {
                        "name": "Shipping Charges",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 13
                    },
                    "14": {
                        "name": "Handling Charges",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 14
                    },
                    "15": {
                        "name": "Tax 1",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 15
                    },
                    "16": {
                        "name": "Tax 2",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 16
                    },
                    "17": {
                        "name": "Custom Field Value Set",
                        "relatedService": {
                            "success": true,
                            "message": null,
                            "showMessageAsAlert": false,
                            "async": false,
                            "name": "Purchasing Custom Fields",
                            "attributes": [
                                {
                                    "name": "Name",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 0
                                },
                                {
                                    "name": "Label",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 1
                                },
                                {
                                    "name": "Distribution Type",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 2
                                },
                                {
                                    "name": "Distribution Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 3
                                },
                                {
                                    "name": "Distribution Split Index",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 4
                                },
                                {
                                    "name": "Distribution Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 5
                                },
                                {
                                    "name": "Shipping Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 6
                                },
                                {
                                    "name": "Handling Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 7
                                },
                                {
                                    "name": "Tax 1 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 8
                                },
                                {
                                    "name": "Tax 2 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 9
                                },
                                {
                                    "name": "Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 10
                                },
                                {
                                    "name": "Description",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 11
                                }
                            ],
                            "serviceFilterParameters": null,
                            "contextInfo": {},
                            "attributeConfigurationForIndexMap": {
                                "0": {
                                    "name": "Name",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 0
                                },
                                "1": {
                                    "name": "Label",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 1
                                },
                                "2": {
                                    "name": "Distribution Type",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 2
                                },
                                "3": {
                                    "name": "Distribution Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 3
                                },
                                "4": {
                                    "name": "Distribution Split Index",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 4
                                },
                                "5": {
                                    "name": "Distribution Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 5
                                },
                                "6": {
                                    "name": "Shipping Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 6
                                },
                                "7": {
                                    "name": "Handling Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 7
                                },
                                "8": {
                                    "name": "Tax 1 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 8
                                },
                                "9": {
                                    "name": "Tax 2 Split Amount",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 9
                                },
                                "10": {
                                    "name": "Value",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 10
                                },
                                "11": {
                                    "name": "Description",
                                    "attributeType": "Text",
                                    "create": false,
                                    "createRequired": false,
                                    "update": false,
                                    "updateRequired": false,
                                    "search": false,
                                    "searchRequired": false,
                                    "attributeIndex": 11
                                }
                            },
                            "dependentLists": null,
                            "platformVersion": "5.5"
                        },
                        "attributeType": "Relationship",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 17
                    },
                    "18": {
                        "name": "UNSPSC",
                        "attributeType": "Text",
                        "create": false,
                        "createRequired": false,
                        "update": false,
                        "updateRequired": false,
                        "search": false,
                        "searchRequired": false,
                        "attributeIndex": 18
                    }
                },
                "dependentLists": null,
                "platformVersion": "5.5"
            },
            "attributeType": "Relationship",
            "create": false,
            "createRequired": false,
            "update": false,
            "updateRequired": false,
            "search": false,
            "searchRequired": false,
            "attributeIndex": 19
        }
    ],
    "serviceFilterParameters": null,
    "contextInfo": {},
    "dependentLists": null,
    "platformVersion": "5.5"
}`

var Config1DataSetItem = `{"primaryKey":"1969540","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"2017-06-06 21:57:02","1879362","John","Muse","john.c.muse@rice.edu","1-713-3485938","PO Box 1892","Houston","TX","77251-1892","US","United States","1700 Rice Blvd","Houston","TX","77005-1892","US","United States",[{"primaryKey":"4609091","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"Approved","1",null,"PR3 Test PR for AppTree integration","EA",null,"0",null,"1","5859291","N","1.00","0.00","0.00","0","0",[{"primaryKey":"Account","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Account","Account",null,null,null,null,null,null,null,null,"72200","Supplies: Shop Supplies and Parts"]},{"primaryKey":"NewCustomField 1","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["NewCustomField 1","PI Authorization",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Activity","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Activity","Activity",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Chart","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Chart","Chart",null,null,null,null,null,null,null,null,"1","Chart"]},{"primaryKey":"Fund","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Fund","Fund",null,null,null,null,null,null,null,null,"A1","Current Unrestricted Fund"]},{"primaryKey":"Bank Code","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Bank Code","Bank Code",null,null,null,null,null,null,null,null,"11","11"]},{"primaryKey":"Organization","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Organization","Organization",null,null,null,null,null,null,null,null,"680070","FE&amp;P Campus Planning"]},{"primaryKey":"Program","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Program","Program",null,null,null,null,null,null,null,null,"MNT","Operation &amp; Maintenance of Plant"]},{"primaryKey":"Location","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Location","Location",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"RiceIndex","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["RiceIndex","RiceIndex",null,null,null,null,null,null,null,null,"A1-680070","Current Unrestricted Fund-FE&amp;P Campus Planning"]},{"primaryKey":"Crew","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Crew","Crew",null,null,null,null,null,null,null,null,"00",""]},{"primaryKey":"WorkOrderNumber","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["WorkOrderNumber","Work Order Number",null,null,null,null,null,null,null,null,"F1365852","TEST FOR WO INTERFACE"]},{"primaryKey":"Index","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Index","Super User",null,null,null,null,null,null,null,null,"HMMGR","Default Super User"]}]]}],null,"jcm9","125769","Grainger","1762",null,"BU Business 1","F-MSS"]}`
var Config1DataSetItemTxtChange = `{"primaryKey":"1969540","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"2017-06-06 21:57:02","1879363","John","Muse","john.c.muse@rice.edu","1-713-3485938","PO Box 1892","Houston","TX","77251-1892","US","United States","1700 Rice Blvd","Houston","TX","77005-1892","US","United States",[{"primaryKey":"4609091","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"Approved","1",null,"PR3 Test PR for AppTree integration","EA",null,"0",null,"1","5859291","N","1.00","0.00","0.00","0","0",[{"primaryKey":"Account","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Account","Account",null,null,null,null,null,null,null,null,"72200","Supplies: Shop Supplies and Parts"]},{"primaryKey":"NewCustomField 1","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["NewCustomField 1","PI Authorization",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Activity","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Activity","Activity",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Chart","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Chart","Chart",null,null,null,null,null,null,null,null,"1","Chart"]},{"primaryKey":"Fund","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Fund","Fund",null,null,null,null,null,null,null,null,"A1","Current Unrestricted Fund"]},{"primaryKey":"Bank Code","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Bank Code","Bank Code",null,null,null,null,null,null,null,null,"11","11"]},{"primaryKey":"Organization","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Organization","Organization",null,null,null,null,null,null,null,null,"680070","FE&amp;P Campus Planning"]},{"primaryKey":"Program","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Program","Program",null,null,null,null,null,null,null,null,"MNT","Operation &amp; Maintenance of Plant"]},{"primaryKey":"Location","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Location","Location",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"RiceIndex","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["RiceIndex","RiceIndex",null,null,null,null,null,null,null,null,"A1-680070","Current Unrestricted Fund-FE&amp;P Campus Planning"]},{"primaryKey":"Crew","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Crew","Crew",null,null,null,null,null,null,null,null,"00",""]},{"primaryKey":"WorkOrderNumber","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["WorkOrderNumber","Work Order Number",null,null,null,null,null,null,null,null,"F1365852","TEST FOR WO INTERFACE"]},{"primaryKey":"Index","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Index","Super User",null,null,null,null,null,null,null,null,"HMMGR","Default Super User"]}]]}],null,"jcm9","125769","Grainger","1762",null,"BU Business 1","F-MSS"]}`
var Config1DataSetItemDteChange = `{"primaryKey":"1969540","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"2017-06-06 21:58:02","1879362","John","Muse","john.c.muse@rice.edu","1-713-3485938","PO Box 1892","Houston","TX","77251-1892","US","United States","1700 Rice Blvd","Houston","TX","77005-1892","US","United States",[{"primaryKey":"4609091","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"Approved","1",null,"PR3 Test PR for AppTree integration","EA",null,"0",null,"1","5859291","N","1.00","0.00","0.00","0","0",[{"primaryKey":"Account","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Account","Account",null,null,null,null,null,null,null,null,"72200","Supplies: Shop Supplies and Parts"]},{"primaryKey":"NewCustomField 1","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["NewCustomField 1","PI Authorization",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Activity","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Activity","Activity",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Chart","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Chart","Chart",null,null,null,null,null,null,null,null,"1","Chart"]},{"primaryKey":"Fund","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Fund","Fund",null,null,null,null,null,null,null,null,"A1","Current Unrestricted Fund"]},{"primaryKey":"Bank Code","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Bank Code","Bank Code",null,null,null,null,null,null,null,null,"11","11"]},{"primaryKey":"Organization","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Organization","Organization",null,null,null,null,null,null,null,null,"680070","FE&amp;P Campus Planning"]},{"primaryKey":"Program","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Program","Program",null,null,null,null,null,null,null,null,"MNT","Operation &amp; Maintenance of Plant"]},{"primaryKey":"Location","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Location","Location",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"RiceIndex","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["RiceIndex","RiceIndex",null,null,null,null,null,null,null,null,"A1-680070","Current Unrestricted Fund-FE&amp;P Campus Planning"]},{"primaryKey":"Crew","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Crew","Crew",null,null,null,null,null,null,null,null,"00",""]},{"primaryKey":"WorkOrderNumber","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["WorkOrderNumber","Work Order Number",null,null,null,null,null,null,null,null,"F1365852","TEST FOR WO INTERFACE"]},{"primaryKey":"Index","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Index","Super User",null,null,null,null,null,null,null,null,"HMMGR","Default Super User"]}]]}],null,"jcm9","125769","Grainger","1762",null,"BU Business 1","F-MSS"]}`
var Config1DataSetItemRelChange = `{"primaryKey":"1969540","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"2017-06-06 21:57:02","1879362","John","Muse","john.c.muse@rice.edu","1-713-3485938","PO Box 1892","Houston","TX","77251-1892","US","United States","1700 Rice Blvd","Houston","TX","77005-1892","US","United States",[{"primaryKey":"4609091","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":[null,"Pending","1",null,"PR3 Test PR for AppTree integration","EA",null,"0",null,"1","5859291","N","1.00","0.00","0.00","0","0",[{"primaryKey":"Account","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Account","Account",null,null,null,null,null,null,null,null,"72200","Supplies: Shop Supplies and Parts"]},{"primaryKey":"NewCustomField 1","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["NewCustomField 1","PI Authorization",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Activity","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Activity","Activity",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"Chart","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Chart","Chart",null,null,null,null,null,null,null,null,"1","Chart"]},{"primaryKey":"Fund","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Fund","Fund",null,null,null,null,null,null,null,null,"A1","Current Unrestricted Fund"]},{"primaryKey":"Bank Code","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Bank Code","Bank Code",null,null,null,null,null,null,null,null,"11","11"]},{"primaryKey":"Organization","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Organization","Organization",null,null,null,null,null,null,null,null,"680070","FE&amp;P Campus Planning"]},{"primaryKey":"Program","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Program","Program",null,null,null,null,null,null,null,null,"MNT","Operation &amp; Maintenance of Plant"]},{"primaryKey":"Location","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Location","Location",null,null,null,null,null,null,null,null,"",""]},{"primaryKey":"RiceIndex","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["RiceIndex","RiceIndex",null,null,null,null,null,null,null,null,"A1-680070","Current Unrestricted Fund-FE&amp;P Campus Planning"]},{"primaryKey":"Crew","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Crew","Crew",null,null,null,null,null,null,null,null,"00",""]},{"primaryKey":"WorkOrderNumber","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["WorkOrderNumber","Work Order Number",null,null,null,null,null,null,null,null,"F1365852","TEST FOR WO INTERFACE"]},{"primaryKey":"Index","CRUDStatus":"READ","clientKey":null,"recordType":"RECORD","status":"NONE","attributes":["Index","Super User",null,null,null,null,null,null,null,null,"HMMGR","Default Super User"]}]]}],null,"jcm9","125769","Grainger","1762",null,"BU Business 1","F-MSS"]}`
